### ISSUE TITLE
Witch potion effects 1.17

### ISSUE THREAD

**Issue by echohunter221** [UltrusBot/MobOrigins#14]
In the latest version as of 6/17/21, the witches potion effects are swapped for falling and swimming. You gain the slow fall potion when swimming and the water breathing potion effect when falling. I'm fairly certain that's not intended. Fire resistance still works though.

**Comment by echohunter221** [comment]
Yeah it looks like you literally just swapped the effects accidentally, potion_action is the class  file, just slow_falling and water_breathing were swapped around in the triggering effects.

**Comment by vos6434** [comment]
also theres no sprting potion

**Comment by SebaSphere** [comment]
> Yeah it looks like you literally just swapped the effects accidentally, potion_action is the class file, just slow_falling and water_breathing were swapped around in the triggering effects.

Fixed as per this PR here: https://github.com/UltrusBot/MobOrigins/pull/17 😃
